version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python3 manage.py runservere 0.0.0.0:8000